# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

use_frameworks!

source "https://github.com/Nexmo/PodSpec.git"
source 'git@github.com:CocoaPods/Specs.git'

def nexmoConversationPod
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    pod "NexmoConversation", :git => "https://github.com/nexmo/conversation-ios-sdk.git", :branch => "master" # development
end

target 'QuickStartOne' do
  nexmoConversationPod
end

target 'QuickStartTwo' do
    nexmoConversationPod
end
