platform :ios, '9.0'

use_frameworks!

source 'git@github.com:CocoaPods/Specs.git'

def nexmoConversationPod
    pod "Nexmo-Stitch"
end

target 'QuickStartOne' do
  nexmoConversationPod
end

target 'QuickStartTwo' do
    nexmoConversationPod
end
