platform :ios, '9.0'

use_frameworks!

source "https://github.com/Nexmo/PodSpec.git"
source 'git@github.com:CocoaPods/Specs.git'

def nexmoConversationPod
    pod "NexmoConversation", :git => "https://github.com/nexmo/conversation-ios-sdk.git", :branch => "master" # development
end

target 'QuickStartOne' do
  nexmoConversationPod
end

target 'QuickStartTwo' do
    nexmoConversationPod
end
