# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

source 'https://github.com/Nexmo/stitch-ios-sdk.git'
source 'https://github.com/CocoaPods/Specs.git'


target 'QuickStartThree' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for QuickStartThree
  pod 'Stitch'

end
